java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:564)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:580)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:670)
	at java.base/java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:3149)
	at genericTest1.main(/home/user/fortress/ProjectFortress/tests/genericTest1.fss)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at com.sun.fortress.runtimeSystem.MainWrapper.main(MainWrapper.java:68)
Caused by: java.lang.NoClassDefFoundError: genericTest1$n
	at genericTest1?$f?1??$\=?Arrow??,com\|sun\|fortress\|compiler\|runtimeValues\|FZZ32?.the_function(Unknown Source)
	at genericTest1?$f?1??$\=?Arrow??,com\|sun\|fortress\|compiler\|runtimeValues\|FZZ32?.apply(Unknown Source)
	at genericTest1.run(/home/user/fortress/ProjectFortress/tests/genericTest1.fss)
	at genericTest1.compute(/home/user/fortress/ProjectFortress/tests/genericTest1.fss)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.ClassNotFoundException: IO Exception in reading class file: 
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.loadClass(InstantiatingClassloader.java:347)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 9 more
Caused by: java.io.IOException: Resource not found : genericTest1$n.class
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.readResource(InstantiatingClassloader.java:152)
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.readResource(InstantiatingClassloader.java:139)
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.getClass(InstantiatingClassloader.java:171)
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.loadClass(InstantiatingClassloader.java:294)
	... 10 more
