FortressException: class fortress.CompilerLibrary$MatchFailure with string Match failure
	at XXXtypecaseTest.run(/home/user/fortress/ProjectFortress/tests/XXXtypecaseTest.fss:0)
	at XXXtypecaseTest.compute(/home/user/fortress/ProjectFortress/tests/XXXtypecaseTest.fss)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
