FortressException: class fortress.CompilerLibrary$MatchFailure with string Match failure
	at XXXcaseTest.test1(/home/user/fortress-rendering/ProjectFortress/tests/XXXcaseTest.fss:0)
	at XXXcaseTest.run(/home/user/fortress-rendering/ProjectFortress/tests/XXXcaseTest.fss:24)
	at XXXcaseTest.compute(/home/user/fortress-rendering/ProjectFortress/tests/XXXcaseTest.fss)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
