"""Compose runnable components from src/MicroGPT.fss and driver fragments.

build/Check.fss = component header + MicroGPT.fss body without its (* TESTS *)
region + src/check_main.part. No Fortress API file is needed (the interpreter
mis-unifies nat-generic functions across an API boundary; see notes).
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src'); BUILD = os.path.join(HERE, '..', 'build')
os.makedirs(BUILD, exist_ok=True)

LIB = sys.argv[1] if len(sys.argv) > 1 else os.path.join(SRC, 'MicroGPT.fss')
PART = sys.argv[2] if len(sys.argv) > 2 else 'check_main.part'
NAME = sys.argv[3] if len(sys.argv) > 3 else 'Check'
lib = open(LIB).read()
# strip component header lines and the final 'end'
lines = lib.split('\n')
body = []
for ln in lines:
    if re.match(r'^(component|import|export)\b', ln): continue
    body.append(ln)
body = '\n'.join(body).rstrip()
assert body.endswith('end'); body = body[:-3].rstrip() + '\n'
# drop the test region
body = re.sub(r'\(\* TESTS \*\).*?\(\* END TESTS \*\)\n?', '', body, flags=re.S)

def compose(name, imports, part):
    hdr = 'component %s\n%s\nexport Executable\n' % (name, '\n'.join(imports))
    frag = open(os.path.join(SRC, part)).read()
    out = ('(* GENERATED by tools/build.py: MicroGPT.fss (minus its test region) + %s *)\n' % part
           + hdr + '\n' + body + '\n' + frag + '\nend\n')
    dest = os.path.join(BUILD, name + '.fss')
    dest = os.path.join(BUILD, name + '.fss')
    open(dest, 'w').write(out)
    print('wrote', dest, len(out.split('\n')), 'lines')

compose(NAME, ['import FortressLibrary.{...} except { opr BIG + }', 'import List.{...}', 'import Set.{...}', 'import MicroGPTData.{...}'], PART)
