"""Generate the Fortress data component MicroGPTData.{fsi,fss} from checks JSON.

Numbers are emitted as decimal expansions of Python's shortest round-trip repr
(Fortress numerals have no exponent notation), which parse back to the same double.
"""
import json, os, sys
from decimal import Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src')
checks = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', 'checks', 'checks_2steps.json')
d = json.load(open(checks))

def num(x):
    r = repr(float(x))
    if 'e' in r or 'E' in r:
        r = format(Decimal(r), 'f')
    if '.' not in r:
        r += '.0'
    return r

def lst(xs):   # List[\RR64\]
    return '<|[\\RR64\\] ' + ', '.join(num(x) for x in xs) + '|>'
def mat(rows): # List[\List[\RR64\]\]
    return '<|[\\List[\\RR64\\]\\]\n    ' + ',\n    '.join(lst(r) for r in rows) + ' |>'
def ints(xs):
    return '<|[\\ZZ32\\] ' + ', '.join(str(int(x)) for x in xs) + '|>'

fsi, fss = [], []
def decl(sig, body):
    sig = 'ref_' + sig   # prefix avoids clashes with the model's own names (no shadowing in Fortress)
    fsi.append(sig)
    fss.append(sig + ' = ' + body)

cfg = d['config']
decl('uchars: String', '"%s"' % cfg['uchars'])
decl('bos: ZZ32', str(cfg['BOS']))
decl('vocab_size: ZZ32', str(cfg['vocab_size']))
decl('n_embd: ZZ32', str(cfg['n_embd']))
decl('n_head: ZZ32', str(cfg['n_head']))
decl('n_layer: ZZ32', str(cfg['n_layer']))
decl('block_size: ZZ32', str(cfg['block_size']))
decl('source_sha256: String', '"%s"' % d['source_sha256'])

names = list(d['init'].keys())
def fname(k): return k.replace('.', '_')
for k in names:
    decl('init_%s(): List[\\List[\\RR64\\]\\]' % fname(k), mat(d['init'][k]))

decl('num_steps: ZZ32', str(len(d['steps'])))
def lst3(cubes):  # List[\List[\List[\RR64\]\]\]
    return '<|[\\List[\\List[\\RR64\\]\\]\\]\n  ' + ',\n  '.join(mat(c) for c in cubes) + ' |>'
def lst2i(rows):
    return '<|[\\List[\\ZZ32\\]\\] ' + ', '.join(ints(r) for r in rows) + '|>'
def strs(xs):
    return '<|[\\String\\] ' + ', '.join('"%s"' % x for x in xs) + '|>'
steps = d['steps']
decl('docs(): List[\\String\\]', strs([st['doc'] for st in steps]))
decl('docs_head(): List[\\String\\]', strs(d['docs_head']))
decl('tokens(): List[\\List[\\ZZ32\\]\\]', lst2i([st['tokens'] for st in steps]))
decl('logits(): List[\\List[\\List[\\RR64\\]\\]\\]', lst3([[p['logits'] for p in st['positions']] for st in steps]))
decl('losses(): List[\\List[\\RR64\\]\\]', mat([[p['loss'] for p in st['positions']] for st in steps]))
decl('loss(): List[\\RR64\\]', lst([st['loss'] for st in steps]))
decl('lr(): List[\\RR64\\]', lst([st['lr_t'] for st in steps]))
for k in names:
    decl('grad_%s(): List[\\List[\\List[\\RR64\\]\\]\\]' % fname(k), lst3([st['grads'][k] for st in steps]))
    decl('after_%s(): List[\\List[\\List[\\RR64\\]\\]\\]' % fname(k), lst3([st['params_after'][k] for st in steps]))

inf = d['inference']
smps = inf['samples']
decl('temperature: RR64', num(inf['temperature']))
decl('num_samples: ZZ32', str(len(smps)))
decl('sample_text(): List[\\String\\]', strs([s['text'] for s in smps]))
decl('sample_draws(): List[\\List[\\RR64\\]\\]', mat([[u for st in s['steps'] for u in st['draw']] for s in smps]))
decl('sample_tokens(): List[\\List[\\ZZ32\\]\\]', lst2i([[st['token'] for st in s['steps']] for s in smps]))
decl('sample_probs(): List[\\List[\\List[\\RR64\\]\\]\\]', lst3([[st['probs'] for st in s['steps']] for s in smps]))

open(os.path.join(SRC, 'MicroGPTData.fsi'), 'w').write(
    'api MicroGPTData\nimport List.{...}\n' + '\n'.join(fsi) + '\nend\n')
open(os.path.join(SRC, 'MicroGPTData.fss'), 'w').write(
    '(* GENERATED by tools/gen_data.py from %s; do not edit. *)\ncomponent MicroGPTData\nimport List.{...}\nexport MicroGPTData\n' % os.path.basename(checks)
    + '\n'.join(fss) + '\nend\n')
print('wrote MicroGPTData.fsi/.fss:', len(fsi), 'declarations')
