"""Generate src/MicroGPTRef.fss and src/MicroGPTRef.fsi from checks/goldens_2steps.json.

The fixture keeps the reference's own layout (Karpathy's matrices, row = output unit) so that the
convention bridge to the program's row-vector form is visible in the program, not hidden here.
Numerals: Fortress has no exponent notation, so a value whose shortest repr needs one is written
as its exact decimal expansion (both parse back to the same double).
"""
import json, os, sys
from decimal import Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'checks', 'goldens_2steps.json')
d = json.load(open(SRC))

def num(x):
    r = repr(float(x))
    if 'e' in r or 'E' in r:
        r = format(Decimal(x), 'f')
    if r.startswith('.'): r = '0' + r
    if r.startswith('-.'): r = '-0' + r[1:]
    return r

def lst(xs): return '<|[\\RR64\\] ' + ', '.join(num(x) for x in xs) + '|>'
def mat(rows): return '<|[\\List[\\RR64\\]\\]\n    ' + ',\n    '.join(lst(r) for r in rows) + '|>'
def ints(xs): return '<|[\\ZZ32\\] ' + ', '.join(str(x) for x in xs) + '|>'
def strs(xs): return '<|[\\String\\] ' + ', '.join('"%s"' % x for x in xs) + '|>'

names = list(d['init'].keys())
cfg = d['config']
steps = d['steps']
samples = d['inference']['samples']

fss = ['(* GENERATED by tools/gen_fixture.py from checks/goldens_2steps.json; do not edit.',
       '   Goldens derived from the pinned reference, see tools/derive_goldens.py. *)',
       'component MicroGPTRef', 'import List.{...}', 'export MicroGPTRef',
       'ref_source_sha256: String = "%s"' % d['source_sha256'],
       'ref_uchars: String = "%s"' % cfg['uchars'],
       'ref_bos: ZZ32 = %d' % cfg['BOS'],
       'ref_vocab_size: ZZ32 = %d' % cfg['vocab_size'],
       'ref_n_embd: ZZ32 = %d' % cfg['n_embd'],
       'ref_n_head: ZZ32 = %d' % cfg['n_head'],
       'ref_block_size: ZZ32 = %d' % cfg['block_size'],
       'ref_num_steps_schedule: ZZ32 = %d' % cfg['num_steps_schedule'],
       'ref_learning_rate: RR64 = %s' % num(cfg['learning_rate']),
       'ref_beta1: RR64 = %s' % num(cfg['beta1']),
       'ref_beta2: RR64 = %s' % num(cfg['beta2']),
       'ref_eps_adam: RR64 = %s' % num(cfg['eps_adam']),
       'ref_num_steps: ZZ32 = %d' % len(steps),
       'ref_temperature: RR64 = %s' % num(d['inference']['temperature']),
       'ref_num_samples: ZZ32 = %d' % len(samples),
       'ref_names(): List[\\String\\] = ' + strs(names)]

def case_by_name(fname, table, extra=''):
    lines = ['%s(%sname: String): List[\\List[\\RR64\\]\\] = case name of' % (fname, extra)]
    for n in names:
        lines.append('    "%s" => %s' % (n, mat(table[n])))
    lines.append('    else => <|[\\List[\\RR64\\]\\] |>')
    lines.append('  end')
    return lines

fss += case_by_name('ref_init', d['init'])
def case_by_step(fname, rtype, f):
    lines = ['%s(step: ZZ32): %s = case step of' % (fname, rtype)]
    for k, s in enumerate(steps):
        lines.append('    %d => %s' % (k, f(s)))
    lines.append('    else => %s' % f(steps[0]).split('\n')[0] if False else '    else => %s' % ('""' if rtype == 'String' else ('0.0' if rtype == 'RR64' else '<|[\\%s\\] |>' % ('ZZ32' if rtype == 'List[\\ZZ32\\]' else ('RR64' if rtype == 'List[\\RR64\\]' else 'List[\\RR64\\]')))))
    lines.append('  end')
    return lines
fss += case_by_step('ref_doc', 'String', lambda s: '"%s"' % s['doc'])
fss += case_by_step('ref_tokens', 'List[\\ZZ32\\]', lambda s: ints(s['tokens']))
fss += case_by_step('ref_logits', 'List[\\List[\\RR64\\]\\]', lambda s: mat(s['logits']))
fss += case_by_step('ref_losses', 'List[\\RR64\\]', lambda s: lst(s['losses']))
fss += case_by_step('ref_loss', 'RR64', lambda s: num(s['loss']))
fss += case_by_step('ref_lr', 'RR64', lambda s: num(s['lr']))
for k, s in enumerate(steps):
    fss += case_by_name('ref_grad%d' % k, s['grads'])
    fss += case_by_name('ref_after%d' % k, s['after'])
fss += ['ref_grad(step: ZZ32, name: String): List[\\List[\\RR64\\]\\] = case step of'] + \
       ['    %d => ref_grad%d(name)' % (k, k) for k in range(len(steps))] + ['    else => <|[\\List[\\RR64\\]\\] |>', '  end']
fss += ['ref_after(step: ZZ32, name: String): List[\\List[\\RR64\\]\\] = case step of'] + \
       ['    %d => ref_after%d(name)' % (k, k) for k in range(len(steps))] + ['    else => <|[\\List[\\RR64\\]\\] |>', '  end']
def case_by_sample(fname, rtype, f, empty):
    lines = ['%s(s: ZZ32): %s = case s of' % (fname, rtype)]
    for k, smp in enumerate(samples):
        lines.append('    %d => %s' % (k, f(smp)))
    lines += ['    else => %s' % empty, '  end']
    return lines
fss += case_by_sample('ref_sample_text', 'String', lambda s: '"%s"' % s['text'], '""')
fss += case_by_sample('ref_sample_tokens', 'List[\\ZZ32\\]', lambda s: ints([st['token'] for st in s['steps']]), '<|[\\ZZ32\\] |>')
fss += case_by_sample('ref_sample_draws', 'List[\\RR64\\]', lambda s: lst([st['draws'][0] for st in s['steps']]), '<|[\\RR64\\] |>')
fss += case_by_sample('ref_sample_probs', 'List[\\List[\\RR64\\]\\]', lambda s: mat([st['probs'] for st in s['steps']]), '<|[\\List[\\RR64\\]\\] |>')
fss.append('end')

fsi = ['api MicroGPTRef', 'import List.{...}']
for line in fss:
    if line.startswith('ref_') and ('=' in line):
        head = line.split(' = ')[0]
        fsi.append(head)
fsi.append('end')
out = os.path.join(HERE, '..', 'src')
open(os.path.join(out, 'MicroGPTRef.fss'), 'w').write('\n'.join(fss) + '\n')
open(os.path.join(out, 'MicroGPTRef.fsi'), 'w').write('\n'.join(fsi) + '\n')
print('wrote src/MicroGPTRef.fss (%d lines) and .fsi (%d lines)' % (len(fss), len(fsi)))
