OK &
FortressException: class fortress.CompilerBuiltin$CompilerFailureDetectedAtRunTime with string Compiler failure detected at runtime
	at fortress.CompilerBuiltin$IntLiteral$DefaultTraitMethods.juxtaposition?0(/home/user/fortress/ProjectFortress/LibraryBuiltin/CompilerBuiltin.fss:837)
	at fortress.CompilerBuiltin$IntLiteral$DefaultTraitMethods.juxtaposition?0(/home/user/fortress/ProjectFortress/LibraryBuiltin/CompilerBuiltin.fss)
	at fortress.CompilerBuiltin.juxtaposition(/home/user/fortress/ProjectFortress/LibraryBuiltin/CompilerBuiltin.fss)
	at ampersand.run(/home/user/fortress/ProjectFortress/tests/ampersand.fss:19)
	at ampersand.compute(/home/user/fortress/ProjectFortress/tests/ampersand.fss)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
