api MicroGPTData
import List.{...}
ref_uchars: String
ref_bos: ZZ32
ref_vocab_size: ZZ32
ref_n_embd: ZZ32
ref_n_head: ZZ32
ref_n_layer: ZZ32
ref_block_size: ZZ32
ref_source_sha256: String
ref_names(): List[\String\]
ref_init_wte(): List[\List[\RR64\]\]
ref_init_wpe(): List[\List[\RR64\]\]
ref_init_lm_head(): List[\List[\RR64\]\]
ref_init_layer0_attn_wq(): List[\List[\RR64\]\]
ref_init_layer0_attn_wk(): List[\List[\RR64\]\]
ref_init_layer0_attn_wv(): List[\List[\RR64\]\]
ref_init_layer0_attn_wo(): List[\List[\RR64\]\]
ref_init_layer0_mlp_fc1(): List[\List[\RR64\]\]
ref_init_layer0_mlp_fc2(): List[\List[\RR64\]\]
ref_num_steps: ZZ32
ref_docs(): List[\String\]
ref_docs_head(): List[\String\]
ref_tokens(): List[\List[\ZZ32\]\]
ref_logits(): List[\List[\List[\RR64\]\]\]
ref_probs(): List[\List[\List[\RR64\]\]\]
ref_losses(): List[\List[\RR64\]\]
ref_loss(): List[\RR64\]
ref_lr(): List[\RR64\]
ref_grad_wte(): List[\List[\List[\RR64\]\]\]
ref_after_wte(): List[\List[\List[\RR64\]\]\]
ref_grad_wpe(): List[\List[\List[\RR64\]\]\]
ref_after_wpe(): List[\List[\List[\RR64\]\]\]
ref_grad_lm_head(): List[\List[\List[\RR64\]\]\]
ref_after_lm_head(): List[\List[\List[\RR64\]\]\]
ref_grad_layer0_attn_wq(): List[\List[\List[\RR64\]\]\]
ref_after_layer0_attn_wq(): List[\List[\List[\RR64\]\]\]
ref_grad_layer0_attn_wk(): List[\List[\List[\RR64\]\]\]
ref_after_layer0_attn_wk(): List[\List[\List[\RR64\]\]\]
ref_grad_layer0_attn_wv(): List[\List[\List[\RR64\]\]\]
ref_after_layer0_attn_wv(): List[\List[\List[\RR64\]\]\]
ref_grad_layer0_attn_wo(): List[\List[\List[\RR64\]\]\]
ref_after_layer0_attn_wo(): List[\List[\List[\RR64\]\]\]
ref_grad_layer0_mlp_fc1(): List[\List[\List[\RR64\]\]\]
ref_after_layer0_mlp_fc1(): List[\List[\List[\RR64\]\]\]
ref_grad_layer0_mlp_fc2(): List[\List[\List[\RR64\]\]\]
ref_after_layer0_mlp_fc2(): List[\List[\List[\RR64\]\]\]
ref_temperature: RR64
ref_num_samples: ZZ32
ref_sample_text(): List[\String\]
ref_sample_draws(): List[\List[\RR64\]\]
ref_sample_tokens(): List[\List[\ZZ32\]\]
ref_sample_probs(): List[\List[\List[\RR64\]\]\]
end
