"""Compose runnable components from src/MicroGPT.fss and a driver fragment.

build/NAME.fss = component header + the body of MicroGPT.fss without its
(* TESTS *) region + src/PART.  The data component MicroGPTData is imported.
(The driver is spliced in rather than importing an API of the core: the check
needs the parameter nodes' grad fields and the core's operators, and a
composed component keeps the core file itself free of verification plumbing.)
Usage: tools/build.py PART NAME
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src'); BUILD = os.path.join(HERE, '..', 'build')
os.makedirs(BUILD, exist_ok=True)
part = sys.argv[1]; name = sys.argv[2]
lib = open(os.path.join(SRC, 'MicroGPT.fss')).read()
body = '\n'.join(ln for ln in lib.split('\n') if not re.match(r'^(component|import|export)\b', ln)).rstrip()
assert body.endswith('end'); body = body[:-3].rstrip() + '\n'
body = re.sub(r'\(\* TESTS \*\).*?\(\* END TESTS \*\)\n?', '', body, flags=re.S)
hdr = ('component %s\nimport FortressLibrary.{...} except { opr BIG + }\nimport List.{...}\nimport Set.{...}\n'
       'import Map.{...}\nimport Constants.{pi, infinity}\nimport MicroGPTData.{...}\nexport Executable\n' % name)
frag = open(os.path.join(SRC, part)).read()
out = '(* GENERATED by tools/build.py: MicroGPT.fss (minus its test region) + %s *)\n' % part + hdr + '\n' + body + '\n' + frag + '\nend\n'
dest = os.path.join(BUILD, name + '.fss'); open(dest, 'w').write(out)
print('wrote', dest, len(out.split('\n')), 'lines')
