"""Generate src/MicroGPTData.{fsi,fss} from checks/goldens_2steps.json.

Numbers are emitted as decimal expansions of Python's shortest round-trip repr
(Fortress numerals have no exponent notation, ledger row 14); the expansion
parses back to the same double.  Every declaration is prefixed ref_ so the
names cannot collide with the program's own.
"""
import json, os, sys
from decimal import Decimal

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'src')
checks = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, '..', 'checks', 'goldens_2steps.json')
d = json.load(open(checks))

def num(x):
    r = repr(float(x))
    if 'e' in r or 'E' in r:
        r = format(Decimal(r), 'f')
    if '.' not in r:
        r += '.0'
    return r
def lst(xs): return '<|[\\RR64\\] ' + ', '.join(num(x) for x in xs) + '|>'
def mat(rows): return '<|[\\List[\\RR64\\]\\]\n    ' + ',\n    '.join(lst(r) for r in rows) + ' |>'
def cube(cs): return '<|[\\List[\\List[\\RR64\\]\\]\\]\n  ' + ',\n  '.join(mat(c) for c in cs) + ' |>'
def ints(xs): return '<|[\\ZZ32\\] ' + ', '.join(str(int(x)) for x in xs) + '|>'
def ints2(rows): return '<|[\\List[\\ZZ32\\]\\] ' + ', '.join(ints(r) for r in rows) + '|>'
def strs(xs): return '<|[\\String\\] ' + ', '.join('"%s"' % x for x in xs) + '|>'

fsi, fss = [], []
def decl(sig, body):
    sig = 'ref_' + sig
    fsi.append(sig); fss.append(sig + ' = ' + body)

cfg = d['config']
decl('uchars: String', '"%s"' % cfg['uchars'])
decl('bos: ZZ32', str(cfg['BOS']))
decl('vocab_size: ZZ32', str(cfg['vocab_size']))
decl('n_embd: ZZ32', str(cfg['n_embd']))
decl('n_head: ZZ32', str(cfg['n_head']))
decl('n_layer: ZZ32', str(cfg['n_layer']))
decl('block_size: ZZ32', str(cfg['block_size']))
decl('source_sha256: String', '"%s"' % d['source_sha256'])
names = list(d['init'].keys())
decl('names(): List[\\String\\]', strs(names))
def fname(k): return k.replace('.', '_')
for k in names:
    decl('init_%s(): List[\\List[\\RR64\\]\\]' % fname(k), mat(d['init'][k]))
steps = d['steps']
decl('num_steps: ZZ32', str(len(steps)))
decl('docs(): List[\\String\\]', strs([st['doc'] for st in steps]))
decl('docs_head(): List[\\String\\]', strs(d['docs_head']))
decl('tokens(): List[\\List[\\ZZ32\\]\\]', ints2([st['tokens'] for st in steps]))
decl('logits(): List[\\List[\\List[\\RR64\\]\\]\\]', cube([[p['logits'] for p in st['positions']] for st in steps]))
decl('probs(): List[\\List[\\List[\\RR64\\]\\]\\]', cube([[p['probs'] for p in st['positions']] for st in steps]))
decl('losses(): List[\\List[\\RR64\\]\\]', mat([[p['loss'] for p in st['positions']] for st in steps]))
decl('loss(): List[\\RR64\\]', lst([st['loss'] for st in steps]))
decl('lr(): List[\\RR64\\]', lst([st['lr_t'] for st in steps]))
for k in names:
    decl('grad_%s(): List[\\List[\\List[\\RR64\\]\\]\\]' % fname(k), cube([st['grads'][k] for st in steps]))
    decl('after_%s(): List[\\List[\\List[\\RR64\\]\\]\\]' % fname(k), cube([st['params_after'][k] for st in steps]))
inf = d['inference']; smps = inf['samples']
decl('temperature: RR64', num(inf['temperature']))
decl('num_samples: ZZ32', str(len(smps)))
decl('sample_text(): List[\\String\\]', strs([s['text'] for s in smps]))
decl('sample_draws(): List[\\List[\\RR64\\]\\]', mat([[u for st in s['steps'] for u in st['draw']] for s in smps]))
decl('sample_tokens(): List[\\List[\\ZZ32\\]\\]', ints2([[st['token'] for st in s['steps']] for s in smps]))
decl('sample_probs(): List[\\List[\\List[\\RR64\\]\\]\\]', cube([[st['probs'] for st in s['steps']] for s in smps]))

open(os.path.join(SRC, 'MicroGPTData.fsi'), 'w').write('api MicroGPTData\nimport List.{...}\n' + '\n'.join(fsi) + '\nend\n')
open(os.path.join(SRC, 'MicroGPTData.fss'), 'w').write(
    '(* GENERATED by tools/gen_data.py from %s (derived from the pinned microgpt.py by reference/derive.py); do not edit. *)\n'
    'component MicroGPTData\nimport List.{...}\nexport MicroGPTData\n' % os.path.basename(checks) + '\n'.join(fss) + '\nend\n')
print('wrote src/MicroGPTData.fsi/.fss:', len(fsi), 'declarations')
