Exception in thread "main" java.lang.NoClassDefFoundError: Treap$Treap
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3010)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2420)
	at com.sun.fortress.runtimeSystem.MainWrapper.main(MainWrapper.java:65)
Caused by: java.lang.ClassNotFoundException: IO Exception in reading class file: 
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.loadClass(InstantiatingClassloader.java:347)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 4 more
Caused by: java.io.IOException: Resource not found : Treap$Treap.class
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.readResource(InstantiatingClassloader.java:152)
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.readResource(InstantiatingClassloader.java:139)
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.getClass(InstantiatingClassloader.java:171)
	at com.sun.fortress.runtimeSystem.InstantiatingClassloader.loadClass(InstantiatingClassloader.java:294)
	... 5 more
