#!/usr/bin/env python3
"""Write microgpt-phase.md from the compile outputs of the two microGPT programs.

Reads  microgpt-results.tsv (corpus-dir, file, rc, secs), written by microgpt-phase.sh
       raw/microgpt/<file>.compile
Writes microgpt-phase.md

The phase is decided by the same classifier the ladder uses (classify.py in this
directory), so a phase here is the same kind of claim as a phase in ladder.tsv.
"""
import os, sys, re, importlib.util

ROOT = os.path.dirname(os.path.abspath(__file__))
TSV = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "microgpt-results.tsv")
RAW = os.path.join(ROOT, "raw", "microgpt")

# import classify.py without running its main()
src = open(os.path.join(ROOT, "classify.py")).read().replace("\nmain()", "\n")
mod = type(sys)("classify_lib")
mod.__dict__["__file__"] = os.path.join(ROOT, "classify.py")
exec(compile(src, "classify.py", "exec"), mod.__dict__)

ORDER = ["parse", "disambiguate", "typecheck", "codegen", "compile-other", "timeout", "pass"]

rows = []
for line in open(TSV):
    f = line.rstrip("\n").split("\t")
    if len(f) < 4:
        continue
    d, name, rc, secs = f[:4]
    text = open(os.path.join(RAW, name + ".compile"), errors="replace").read()
    phase, err = mod.classify_compile(int(rc), text)
    if phase is None:
        phase, err = "pass", ""          # compile exited 0; nothing was run
    rows.append((d, name, int(rc), secs, phase, mod.norm(err)))

def esc(s):
    return s.replace("|", "\\|")

L = []
w = L.append
w("<!-- Generated by microgpt-phase.py from the compile outputs under raw/microgpt/. -->")
w("")
w("# The two microGPT programs on the compile path")
w("")
w("The measuring stick of the compile-path work: `explorations/run-c4/src` (the flat")
w("Run C4 model) and `explorations/apl/mg` (the APL-notation port). Every component and")
w("api of both, pushed through `fortress compile` in dependency order, in the same")
w("private cache as the ladder, immediately after the ladder run of this directory.")
w("")
w("`phase` is decided by `classify.py`, the ladder's own classifier, so these rows are")
w("the same kind of claim as a row of `ladder.tsv`. Only `fortress compile` was run;")
w("nothing was linked or run, so `pass` here means the component compiled, not that it")
w("produced an answer.")
w("")
w("Per file: `fortress compile <file>` from the file's own directory, 300 s timeout.")
w("")
for d in ["explorations/run-c4/src", "explorations/apl/mg"]:
    sub = [r for r in rows if r[0] == d]
    if not sub:
        continue
    w("## `%s`" % d)
    w("")
    w("| # | file | phase | rc | secs | first error, verbatim |")
    w("|---|---|---|---|---|---|")
    for i, (_, name, rc, secs, phase, err) in enumerate(sub, 1):
        w("| %d | `%s` | %s | %d | %s | %s |" % (i, name, phase, rc, secs, esc(err) or "(none)"))
    w("")
    reached = [p for p in ORDER if any(r[4] == p for r in sub)]
    w("Phases reached: " + ", ".join(
        "%s %d" % (p, sum(1 for r in sub if r[4] == p)) for p in reached) + ".")
    w("")
open(os.path.join(ROOT, "microgpt-phase.md"), "w").write("\n".join(L) + "\n")
for r in rows:
    print(r[0], r[1], r[4], "rc=%d" % r[2], r[5][:90])
