#!/usr/bin/env python3
"""Write pass-list.txt and MOVES.md from this run's ladder.tsv against ../after/ladder.tsv.

pass-list.txt  one line per file that reaches `pass`, with the path of its captured stdout
MOVES.md       every file whose phase differs from ../after/ladder.tsv, with both phases
               and this run's first error line, plus the pass counts of both runs
"""
import os, csv, collections

ROOT = os.path.dirname(os.path.abspath(__file__))
AFTER = os.path.join(ROOT, "..", "after")
ORDER = ["parse", "disambiguate", "typecheck", "codegen", "compile-other", "timeout",
         "link", "run", "pass"]
RANK = {p: i for i, p in enumerate(ORDER)}

def load(p):
    return {(r["corpus"], r["file"]): r
            for r in csv.DictReader(open(p), delimiter="\t")}

now = load(os.path.join(ROOT, "ladder.tsv"))
was = load(os.path.join(AFTER, "ladder.tsv"))

# ---- pass-list.txt
rel = "explorations/compile-ladder/%s/raw" % os.path.basename(ROOT)
lines = []
for k in sorted(now):
    corpus, f = k
    if now[k]["phase"] != "pass":
        continue
    ext = ".compile" if f.endswith(".fsi") else ".run"
    lines.append("%s/%s\t%s/%s/%s%s" % (corpus, f, rel, corpus, f, ext))
open(os.path.join(ROOT, "pass-list.txt"), "w").write(
    "# file\tcaptured stdout\n" + "\n".join(lines) + "\n")

# ---- MOVES.md
cn = collections.Counter(r["phase"] for r in now.values() if r["corpus"] == "tests")
cl = collections.Counter(r["phase"] for r in now.values() if r["corpus"] == "not_working_library_tests")
an = collections.Counter(r["phase"] for r in was.values() if r["corpus"] == "tests")
al = collections.Counter(r["phase"] for r in was.values() if r["corpus"] == "not_working_library_tests")

up, down, gone, new = [], [], [], []
for k in sorted(set(now) | set(was)):
    if k not in was:
        new.append(k); continue
    if k not in now:
        gone.append(k); continue
    a, b = was[k]["phase"], now[k]["phase"]
    if a == b:
        continue
    (up if RANK[b] > RANK[a] else down).append(k)

def esc(s):
    return s.replace("|", "\\|")

L = []
w = L.append
w("<!-- Generated by moves.py from this run's ladder.tsv against ../after/ladder.tsv.")
w("     The closing section, \"Where each move comes from\", is written by hand and a")
w("     re-run of moves.py drops it. -->")
w("")
w("# Moves against the climb's re-run")
w("")
w("`../after/ladder.tsv` is the phase table measured at tree `40216550c`, the head of")
w("the eight-rung climb (`../CLIMB.md`). This run used the same driver, corpora,")
w("timeouts and phase vocabulary, so the two tables are comparable file for file.")
w("")
w("## Pass counts")
w("")
w("| corpus | files | pass, `after/` | pass, this run |")
w("|---|---|---|---|")
w("| `tests` | 381 | %d | %d |" % (an["pass"], cn["pass"]))
w("| `not_working_library_tests` | 29 | %d | %d |" % (al["pass"], cl["pass"]))
w("| **total** | **410** | **%d** | **%d** |" % (an["pass"] + al["pass"], cn["pass"] + cl["pass"]))
w("")
w("## Counts per phase")
w("")
w("| phase | tests, `after/` | tests, this run | nwlt, `after/` | nwlt, this run |")
w("|---|---|---|---|---|")
for p in ORDER:
    if an[p] or cn[p] or al[p] or cl[p]:
        w("| %s | %d | %d | %d | %d |" % (p, an[p], cn[p], al[p], cl[p]))
w("")
w("## Files whose phase differs")
w("")
if not up and not down and not new and not gone:
    w("None. Every one of the 410 files reaches the phase it reached in `after/`.")
else:
    w("| file | `after/` | this run | direction | `after/` first error | this run's first error |")
    w("|---|---|---|---|---|---|")
    for k in up + down:
        corpus, f = k
        d = "up" if k in up else "**down**"
        w("| `%s/%s` | %s | %s | %s | %s | %s |"
          % (corpus.replace("not_working_library_tests", "nwlt"), f,
             was[k]["phase"], now[k]["phase"], d,
             esc(was[k]["first_error"]) or "(none)", esc(now[k]["first_error"]) or "(none)"))
    for k in new:
        w("| `%s/%s` | (absent) | %s | new file | | %s |"
          % (k[0], k[1], now[k]["phase"], esc(now[k]["first_error"]) or "(none)"))
    for k in gone:
        w("| `%s/%s` | %s | (absent) | file gone | | |" % (k[0], k[1], was[k]["phase"]))
w("")
w("## Files that kept their phase and changed their first error")
w("")
ch = [k for k in sorted(set(now) & set(was))
      if now[k]["phase"] == was[k]["phase"]
      and now[k]["first_error"] != was[k]["first_error"]]
if not ch:
    w("None.")
else:
    w("| file | phase | `after/` first error | this run's first error |")
    w("|---|---|---|---|")
    for k in ch:
        w("| `%s/%s` | %s | %s | %s |"
          % (k[0].replace("not_working_library_tests", "nwlt"), k[1], now[k]["phase"],
             esc(was[k]["first_error"]) or "(none)", esc(now[k]["first_error"]) or "(none)"))
open(os.path.join(ROOT, "MOVES.md"), "w").write("\n".join(L) + "\n")
print("pass this run: tests %d, nwlt %d, total %d" % (cn["pass"], cl["pass"], cn["pass"] + cl["pass"]))
print("pass after/:   tests %d, nwlt %d, total %d" % (an["pass"], al["pass"], an["pass"] + al["pass"]))
print("moved up %d, moved down %d, new %d, gone %d, same-phase-new-error %d"
      % (len(up), len(down), len(new), len(gone), len(ch)))
